apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hub-provisioner

resources:
  - namespace.yaml
  - ../../../bases/pipelines/hub-provisioner
#  - hub-provisioner.pipelinerun.yaml

